### ISSUE TITLE
Implement tooling (e.g., `pre-commit` hooks) to maintain standards and simplify the review process

### ISSUE THREAD

**Issue by wmalgadey** [wmalgadey/PyTado#103]

**Comment by wmalgadey** [comment]
@palazzem did you have some features in mind, which we could track here in specific?

**Comment by palazzem** [comment]
Yes I think this is something we should have. You can take a look at some pre-commit hooks I'm using here: https://github.com/palazzem/ha-econnect-alarm/blob/main/.pre-commit-config.yaml

What you can do is:
1. Add this file in the repository
2. Include in the README some instructions to set it up ([example](https://github.com/palazzem/ha-econnect-alarm/blob/main/README.md#dev-environment))
3. Before you commit and send the PR out, run `pre-commit autoupdate` from your dev env, so that you'll pull out the latest versions of plugins in the file

You should consider that when you launch these hooks for the first time, a lot of changes may happen as `isort` and `black` will reformat your code base. Happy to give you more details if needed!

Other than that, I'd say that having `pre-commit` hooks is a great start. Hope my comment helps!

**Comment by wmalgadey** [comment]
I would close the issue, because we made some changes and progress I guess
