### ISSUE TITLE
Update repository settings to establish some rules (merging, releases, actions, milestones, roadmap, etc.)

### ISSUE THREAD

**Issue by wmalgadey** [wmalgadey/PyTado#106]
- create the "Road to 1.0" Milestone
- and "Tado X"-Milestone
- added security features to the project
- updated github actions/workflows (incl. tests and coverage)

**Comment by wmalgadey** [comment]
@palazzem are there any other settings we should check/set?

**Comment by palazzem** [comment]
This is a matter of the way software engineers like to write/review and merge code. I prefer using a more linear approach as you see in one of my repos: https://github.com/palazzem/ha-econnect-alarm/commits/main/

Basically I only use the "squash" merging rule so that we merge always 1 merged commit for each PR, using https://www.conventionalcommits.org/en/v1.0.0/ as a description. If it's something you like too, you can update your repo settings to allow only squash merges:
1. Settings > Pull Requests > Allow squash merging
2. Select "Pull Request Title"
3. Disable the rest

I prefer this approach as it is simpler to navigate changes, especially when we should rollback something (or find a regression). But if you prefer another approach, simply ignore my comment!

I'm reviewing the repo in case I have something more to suggest!

**Comment by wmalgadey** [comment]
Done! Squashed PRs are now set. I personally like rebasing better, but that's related to my work, where we use the complete history a lot!

**Comment by palazzem** [comment]
> Done! Squashed PRs are now set. I personally like rebasing better, but that's related to my work, where we use the complete history a lot!

Absolutely! There isn't the perfect tool/approach, just the right tool/approach for the job! That's why programming is so exciting!

**Comment by wmalgadey** [comment]
@palazzem what do you say? can we close this issue? or do you have some more suggestions?

**Comment by palazzem** [comment]
@wmalgadey yes I think we can close the comment! You did a great job here in improving our contribution standards!
