### ISSUE TITLE
Improve tado API definition (https://my.tado.com/api/v2) documentation for tado X

### ISSUE THREAD

**Issue by kritsel** [wmalgadey/PyTado#118]
Hi there,

I'm blatantly abusing a GitHub Issue to reach to you about working together on Tado API documentation. 

I'm the author of the https://github.com/kritsel/tado-openapispec-v2 repo which contains an API definition (OpenAPI schema) for the tado api hosted on https://my.tado.com/api/v2. I would love to extend the documentation of that API definition to indicate which operations are also supported for tado X supported homes and which aren't.

As my home is equiped with tado V3+ devices, I cannot test which https://my.tado.com/api/v2 operations do and don't work for tado X myself. But maybe you guys can help out here. 

Just let me know if you're open to join forces on this one.

Cheers,
Kristel

**Comment by wmalgadey** [comment]
Hi @kritsel,

I sure can help with that. What exactly do you need?

This library already has the new endpoints (hops.tado.com), which seem to replace the old my.tado.com/api/v2 endpoints. Those which do not have a suitable method are decorated with `@not_supported` and all the others are currently working.

**Comment by kritsel** [comment]
Hi @wmalgadey, I'm back after a Christmas break :-)

My ultimate goal is for every tado API operation defined in this Swagger spec https://kritsel.github.io/tado-openapispec-v2/swagger.html (this covers only https://my.tado.com) to indicate if it supports or does not support a tado X enabled home.

Currently several operation groups carry labels that indicate that it is unknown if they support tado X or not. Any help you could provide to decrease the number of unknowns is much appreciated. 

I'm not really used to reading/writing Kotlin code. Could you give me a pointer how I could deduce from your current code base if a certain https://my.tado.com operation is supported by tado X or not. That would help me to do some discovery myself.

**Comment by wmalgadey** [comment]
@kritsel I just tested the api calls without a zone parameter. Those all do work:

- `https://auth.tado.com/oauth/token`
- `https://my.tado.com/api/v2/me`
- `https://my.tado.com/api/v2/homes/<home_id>/`
- `https://my.tado.com/api/v2/homes/<home_id>/state`
- `https://my.tado.com/api/v2/homes/<home_id>/devices`
- `https://my.tado.com/api/v2/homes/<home_id>/zones`
- `https://my.tado.com/api/v2/homes/<home_id>/zoneStates`
- `https://my.tado.com/api/v2/homes/<home_id>/weather`
- `https://my.tado.com/api/v2/homes/<home_id>/airComfort`
- `https://my.tado.com/api/v2/homes/<home_id>/users`
- `https://my.tado.com/api/v2/homes/<home_id>/mobileDevices`
- `https://my.tado.com/api/v2/homes/<home_id>/presenceLock`
- `https://my.tado.com/api/v2/homes/<home_id>/heatingCircuits`

Here are my findings

- I get errors, because I do not have the new subscription for the auto assists features
  `DELETE https://my.tado.com/api/v2/homes/<home_id>/presenceLock`:
  ```json
  {'errors': [{'code': 'accessibleOnlyForHomesWithAutoAssist', 'title': "operation 'remove home presence lock' is not supported for home 12345678 (wolfgang@malgadey.de): home presence locking is available only for homes with AA"}]}
  ```

- There are no zones and zone states anymore! Therefore every call with a zone-id as parameter results in a 404 with this error:
  ```json
  {'errors': [{'code': 'notFound', 'title': 'zone (14) of home 12345678 not found'}]}
  ```
  but I do have a room with the ID 14

- The devices endpoint doesn't find tado X thermostats with serial no `VA34013XXXX`
  `https://my.tado.com/api/v2/devices/<device_id>/`

- The Tado X Bridge has no authKey, therefore the following call fails:
  `https://my.tado.com/api/v2/homeByBridge/IBxxxx?authKey=xxxx`

**Comment by wmalgadey** [comment]
Ahh some zone endpoints do still work 😒 

- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/dayReport?date=2024-12-28&`

But most don't and respond with 404:

- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/state`
- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/defaultOverlay`
- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/capabilities`
- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/schedule/activeTimetable`
- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/state/openWindow/activate`
- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/state/openWindow`
- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/control`
- `https://my.tado.com/api/v2/homes/<home_id>/zones/14/control/heatingCircuit`

**Comment by kritsel** [comment]
Tado engineers design their APIs in mysterious ways...

Thank your very much for your extensive info, much appreciated! I've already translated some of it into labels in the API definition for the my.tado.com API.

Based on your data and data I read elsewhere on various internet forums about tado API support for tado&ordm; X, I'm left with a few open ends as there seem to be some inconsistencies in what I'm reading. Could you maybe help me by doing an additional check for the three operations mentioned below? Each operation represents a different way of determining the devices in a home.
I'm curious to learn which of these produce a meaningful (no error, no empty response/array) response:
  * GET /homes/{homeId}/devices
  * GET /homes/{homeId}/deviceList
  * GET /homes/{homeId}/zones

**Comment by kritsel** [comment]
Forgot one question: GET /homes/{homeId}/installations results in an OK (http 200) response with an empty array for my tado V3+ enabled home. Is that the same for tado X?

**Comment by wmalgadey** [comment]
```
Method:GET
URL: https://my.tado.com/api/v2/homes/1745644/devices
Data: []

URL: https://my.tado.com/api/v2/homes/1745644/devicesList
Data: {'errors': [{'code': 'accessDenied', 'title': 'current user is not allowed to access this resource'}]}

Method:GET
URL: https://my.tado.com/api/v2/homes/1745644/zones
Data: []

Method:GET
URL: https://my.tado.com/api/v2/homes/1745644/installations
Data: []
```

**Comment by kritsel** [comment]
Thanks a lot! Closing this issue now.
